[project]
name = "notify-bot"
version = "0.0.0"
description = "Telegram notification bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.12.0",
    "ruff>=0.14.11",
]
